
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navbar";
import Script from 'next/script';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang="en">
      <head>
       <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
     
       </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        
        <Navbar />
        {children}
      

      </body>
       <Script
          type="module"
          src="https://unpkg.com/@splinetool/viewer@1.9.96/build/spline-viewer.js"
          strategy="afterInteractive"
        />
    </html>
    </ClerkProvider>
  );
}
